config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :tasks do
    member do
      get 'confirm_delete'
      get 'task_completion'
      get 'add_participants', as: :add_participants
      get 'task_up'
      get 'task_down'

    end
    collection do
      get 'active_tasks', :as => :active
      get 'completed_tasks', :as => :completed
      get 'task_requests', :as =>:requests
      post :remove_share
    end
    resources :comments
  end
  resources :participants do
    member do
      get 'accept_request'
      get 'set_progression'
    end
    collection do
      post :set_progression
      get :autocomplete_user_name
      get :check_existence
    end

  end

  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  scope :completed, lambda { |user|
    includes(:participants)
    .order('participants.priority desc')
    .where(participants: { status: 'confirmed', user_id: user.id }, completed: true)
  }
  scope :active, lambda { |user|
    includes(:participants)
    .order('participants.priority desc')
    .where(participants: { status: 'confirmed', user_id: user.id }, completed: false)
  }
  has_many :participants,  dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :users, through: :participants
  accepts_nested_attributes_for :participants, allow_destroy: true
  validates :title, presence: true, length: { minimum: 1 }

  after_create :participant_create
  after_update :toggle_status

  def swap_tasks(user, action)
    participant = user.participants.find_by_task_id(id)
    priority = participant.priority
    if action == 'task_up'
      if completed == true
        other_participant = user.participants.joins(:task)
        .where('participants.priority > ? AND tasks.completed = ?', priority, true)
        .order('priority DESC').last
      else
        other_participant = user.participants.joins(:task)
        .where('participants.priority > ? AND tasks.completed = ?', priority, false)
        .order('priority DESC').last
      end
    else
      if completed == true
        other_participant =  user.participants.joins(:task)
        .where('participants.priority < ? AND tasks.completed = ?', priority, true)
        .order('priority DESC').first
      else
        other_participant =  user.participants.joins(:task)
        .where('participants.priority < ? AND tasks.completed = ?', priority, false)
        .order('priority DESC').first
      end
    end
    swap_priority(participant, other_participant)
  end

  private

  #-- creating participant entry for task author and marking  status as confirmed
  def participant_create
    participations = Participant.order('priority ASC').where(user_id: user_id)
    if participations.count > 0
      last_priority = participations.last.priority.to_i
      priority = last_priority + 1
      Participant.create(user_id: user_id, task_id: id, status: 'confirmed', priority: priority)
    else
      Participant.create(user_id: user_id, task_id: id, status: 'confirmed', priority: 1)
    end
  end
  #--- Toggling task status to completed or not completed ---#
  def toggle_status
    return unless completed_changed?
    user = User.find(user_id)
    if completed == true
      comments.create(user_name: user.name, comment: 'Status changed to <span class = "text-success">Done</span>', commenter: user.id)
    else
      comments.create(user_name: user.name, comment: 'Status changed to <span class = "text-danger">UnDone</span>', commenter: user.id)
    end
  end
  #--swaps priority of two participants ---#
  def swap_priority(first, second)
    first.priority, second.priority = second.priority, first.priority
    first.save!
    second.save!
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_task, except: [:index, :edit, :create, :active_tasks, :completed_tasks, :task_requests, :remove_share]
  before_filter :find_task_list, only: [:task_completion, :destroy, :task_up, :task_down]
  before_filter :find_active_tasks, only: [:index, :create, :active_tasks]
  respond_to :html, :js, :json

  def index
    @task = Task.new
  end

  def show
    @users = User.all
    @participant = current_user.participants.find_by_task_id(params[:id])
    @comments = @task.comments.paginate(page: params[:page], per_page: 10)
  end

  def create
    @task = current_user.tasks.new(task_params)
    @task.user_id = current_user.id
    @save_flag = @task.save
  end

  def update
    if @task.update_attributes(task_params)
      redirect_to task_path(@task.id), notice: 'Task updated Successfully'
    else
      redirect_to task_path(@task.id), notice: 'Task updation Failed'
    end
  end

  def destroy
    @task.destroy
    respond_with(@task) do |format|
      format.html { redirect_to tasks_path }
    end
  end

  def confirm_delete
    @participant = current_user.participants.find_by_task_id(@task.id)
  end

  def active_tasks
  end

  def completed_tasks
    @tasks = Task.completed(current_user).paginate(page: params[:page], per_page: 10)
  end

  def task_requests
    @participants  = Participant.where(status: 'pending', user_id: current_user.id)
    @tasks = Task.all
  end

  def task_completion
    if @task.update_attributes(completed: params[:status])
      respond_with(@task) do |format|
        format.html { redirect_to task_path(params[:id]) }
      end
    else
      redirect_to task_path @task, notice: 'Task completion error'
    end
  end

  def add_participants
  end

  def task_up
    @task.swap_tasks(current_user, 'task_up')
  end

  def task_down
    @task.swap_tasks(current_user, 'task_down')
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def find_task_list
    if @task.completed == true
      @tasks = Task.completed(current_user).paginate(page: params[:page], per_page: 10)
    else
      @tasks = Task.active(current_user).paginate(page: params[:page], per_page: 10)
    end
  end

  def find_active_tasks
    @tasks = Task.active(current_user).paginate(page: params[:page], per_page: 10)
  end

  def task_params
    params.require(:task).permit(:title, participants_attributes:[:id, :user_id, :_destroy])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def total_completion(task)
    total = 0
    count = task.participants.count
    task.participants.each do |participant|
      total += participant.progression
    end
    total/count
  end

  def creator(task)
    User.find(task.user_id)
  end

  def link_extract(text)
    linked = text.gsub( %r{http[s]?://[^\s<]+} ) do |url|
      if url[/(?:png|jpe?g|gif|svg)$/]
        "<img src='#{url}' />"
      else
        "<a href='#{url}'>#{url}</a>"
      end
   end
  end
end

app/views/tasks/_active_tasks.html.erb
<!-- Renders active tasks -->
<div id = "tasks_lists">
  <% if @tasks.count > 0 %>
      <%= render @tasks %>
    <% else %>
      <div class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        You dont have any active tasks.
      </div>
    <% end %>

</div>
<%= will_paginate @tasks %>
<script>
  $(document).ready(function(){
    $('.pagination').hide();
  });
</script>

app/views/tasks/_completed_tasks.html.erb
<!-- Renders Completed tasks in tab pane -->
<div id = "tasks_lists">
  <% if @tasks.count > 0 %>
      <%= render @tasks %>
    <% else %>
      <div class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        You dont have any tasks completed.
      </div>
    <% end %>

</div>
<%= will_paginate @tasks %>
<script>
  $(document).ready(function(){
    $('.pagination').hide();
  });
</script>

app/views/tasks/_confirmation.html.erb
<!-- Task deletion confirmation box -->
<div class="panel-body">
  <div class= "col-sm-12 row">
    <div class="col-sm-8 delete_confirmation">
      Are you sure want to delete this entry ?
    </div>
    <div class="col-sm-4 delete_confirmation">
      <div class = "col-sm-6">
        <% if @task.user_id == current_user.id %>
          <%= link_to ("<div class = 'delete_confirmation_button'>Yes</div>").html_safe, task_path(@task.id) , method: :delete ,remote: true %>
        <% else %>
          <%= link_to ("<div class = 'delete_confirmation_button'>Yes</div>").html_safe, participant_path(@participant.id) , method: :delete ,remote: true %>
        <% end %>
      </div>
      <div class = "col-sm-6">
        <%#= link_to ("<div class = 'delete_confirmation_cancel_button'><u>No</u></div>").html_safe, tasks_path %>
        <div class = 'delete_confirmation_cancel_button'><u>No</u></div>
      </div>
    </div>
  </div>
</div>

<script>
  $('.delete_confirmation_cancel_button').on('click', function(){
    $('.delete_box').hide();
  });
</script>

app/views/tasks/_error_dialog.html.erb
<div class="alert alert-danger">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  Something went wrong, Task creation error
</div>

app/views/tasks/active_tasks.js.erb
<% if params[:page].present?  %>
  $('#tasks_lists').append('<%= escape_javascript render(@tasks) %>');
  <% if @tasks.next_page %>
    $('.pagination').replaceWith('<%= escape_javascript will_paginate(@tasks) %>');
  <%else %>
    $('.pagination').remove();
  <%end%>
<% else %>
  $("#show_tabs").html("<%= escape_javascript(render partial:'active_tasks') %>");
<% end %>

app/views/tasks/completed_tasks.js.erb
<% if params[:page].present?  %>
  $('#tasks_lists').append('<%= escape_javascript (render @tasks) %>');
  <% if @tasks.next_page %>
    $('.pagination').replaceWith('<%= escape_javascript will_paginate(@tasks) %>');
  <%else %>
    $('.pagination').remove();
  <%end%>
<% else %>
  $("#show_tabs").html("<%= escape_javascript(render partial: 'completed_tasks') %>");
<% end %>

app/views/tasks/edit.html.erb
<!-- Modal box for Task Update -->
<div class = "jumbotron">
  <center>
    <h3>Update Task</h3>
  </center>
  <%= form_for @task do |f|%>
    <%=  f.text_field :title, class:'form-control', autofocus:true %>
    <%=  f.text_area :description, class:'form-control', autofocus:true, placeholder:"Enter Description here" %>
    <%= f.submit :submit, value:"Save", class: "btn btn-success form-control" %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<!-- Task Index Page -->
<div id = "error_box" style="display:none;">
</div>

    <%= form_for @task, remote:true do |f| %>
      <div class = 'input-group task'>
        <span class="input-group-addon">
          <span class = "task_add_btn"></span>
        </span>
        <%= f.text_field :title, class:'new_task', autofocus:true, placeholder:"Add your TODO entry, Hit Enter to post", autocomplete: :off %>
    </div>
        <% f.submit :submit %>
    <% end %>
<div id="indextab">
  <ul class="nav nav-tabs nav-justified">
    <li><%= link_to "Active Tasks", active_tasks_path, remote: true, data: {toggle:"tab"} %></li>
    <li><%= link_to "Completed Tasks", completed_tasks_path, remote: true, data: {toggle:"tab"} %></li>
    <li><%= link_to "Task Requests", requests_tasks_path, remote: true, data: {toggle:"tab"} %></li>
  </ul>
</div>
<!-- This div is used for rendering results when clicking above tabs -->
<div id="show_tabs" class = "span9">
  <div id="tasks_lists">
    <% if @tasks.count > 0 %>
      <%= render @tasks %>
    <% else %>
      <div class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        You dont have any tasks assigned.
      </div>
    <% end %>

  </div>
  <%= will_paginate @tasks %>
</div>
<script>
  $(document).ready(function(){
    $('.pagination').hide();
  });
</script>

app/views/tasks/index.js.erb
$('#tasks_lists').append('<%= j render(@tasks) %>');
<% if @tasks.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@tasks) %>');
<%else %>
  $('.pagination').remove();
<%end%>

app/views/tasks/show.html.erb
<div class="panel panel-default row show">
  <div class="panel-body show">
    <div class="col-sm-8">
      <div class = "col-sm-12">
        <div class= "task_title">
          <%= sanitize(link_extract(@task.title)) %>
        </div>

      </div>
      <div class = "col-sm-12">
        <div class = "task_author">
          Created by <b><%= link_to creator(@task).name, user_path(creator(@task).id) %></b>
          <span>
            <% if creator(@task) == current_user %>
              (You)
            <% end %>
          </span>
        </div>
        <div class= "task_date">
          <%= time_ago_in_words(@task.created_at) %>
        </div>
      </div>
    </div>
    <% if @task.user_id == current_user.id %>
          <div class = "task_delete_link pull-right">
            <%= link_to ("<div class = 'delete_button'> </div>").html_safe, task_path(@task.id), data: {confirm: "Are you sure?"}, method: :delete %>
          </div>
    <% end %>
    <div class = "col-sm-12 slider_header">
      Task Completion
    </div>
    <div class = "col-sm-12 task_completion_slider_box row">

      <div class = "pull-left slider_box">

          <div id="slider_group">
              <div id="slider"></div>
              <span id="completion_perc"><%= @participant.progression.to_i %>%</span>
          </div>

      </div>
      <% if @task.user_id == current_user.id %>
        <div class ='pull-right'>
              <% if @task.completed == false %>
                <%= link_to ("<div class = 'task_menu_btn comp_button'> </div>").html_safe, task_completion_task_path(id:@task.id, status:true) %>
              <% else %>
                <%= link_to ("<div class = 'task_menu_btn comp_button completed'> </div>").html_safe, task_completion_task_path(@task.id, status:false) %>
              <% end %>
        </div>
      <% else %>
        <div class ='pull-right'>
              <% if @task.completed == false %>
                <div class = 'task_menu_btn comp_button disabled'> </div>
              <% else %>
                <div class = 'task_menu_btn comp_button completed disabled'> </div>
              <% end %>
        </div>
      <% end %>

    </div>
    <div class = 'col-sm-12'>
      <%#= link_to ("<div class = 'share_link'>Share</div>").html_safe, controller: "tasks", action: "add_participants", id: @task.id , remote: true %>

        <% unless (@task.user_id!= current_user.id) %>
          <%#= link_to_modal ("<div class = 'share_link'>Share</div>").html_safe, add_participants_task_path(@task.id), data:{remote: true} %>
          <div id="example-popup" class="popup">
            <div class="popup-body">
              <%=render 'add_participants' %>
            </div>
          </div>
          <div class="popup-overlay"></div>
          <div class="share_link" data-popup-target="#example-popup">
            Share
          </div>
        <% end %>


    </div>

    <div class = "col-sm-12 shared_people">
        <strong>Shared With :</strong>
        <% @task.participants.each do |participant| %>
          <% next if participant.user_id == current_user.id %>
          <% if participant.status == 'confirmed' %>
            <%= link_to participant.user.name, user_path(participant.user) %>
            <% unless participant == @task.participants.last %>
              &nbsp;
            <% end %>
          <% end %>
        <% end %>
    </div>


  </div>
  <!-- Overall task percentage -->
  <% if @task.user_id == current_user.id %>
      <div class = "overall_progress">
            <a href="#" data-toggle="tooltip" title="<%= total_completion(@task) %>%">
              <div class="progress">
              <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:<%= total_completion(@task) %>%"></div>
            </div>
            </a>
      </div>
  <% end %>
  <!---------------------------------------->
</div>


<div id="task_delete_confirmation" style="display: none; ">

</div>



<div class = 'comments_panel'>
  <ul class="list-group", id="comments_listing">
    <%= render @comments.reverse %>
  </ul>
  <%= will_paginate @comments %>
  <%= render 'comments/form' %>
</div>
<span id= "task_id", display:none>
  <%= @task_id %>
</span>
</form>


<script>
var $slider = $("#slider");
var Count=0;
  $slider.slider({
    min: 0,
    max: 100,
    value: 0,
    orientation: "horizontal",
    range:'min',
    animate: "fast",
    value: '<%= @participant.progression.to_i %>',
    change: function( event, ui ) {
    var progress=$(this).slider("value");
    var id = '<%=@task.id%>'
    $("#completion_perc").html(progress+"%");
    Count++;
    setTimeout(function(){
      Count--;
      if(Count<=0) {
        $.ajax({
        url: '/participants/set_progression',
        method: "POST",
        data: {id:id ,progress:progress }
        });
      }
    }, 1500);

    }

  });
if (<%= @task.completed == true %>) {
  $('#slider').slider({ disabled: true });
}

$(document).ready(function() {

    $('[data-popup-target]').click(function () {
        $('html').addClass('overlay');
        var activePopup = $(this).attr('data-popup-target');
        $(activePopup).addClass('visible');

    });

    $(document).keyup(function (e) {
        if (e.keyCode == 27 && $('html').hasClass('overlay')) {
            clearPopup();
        }
    });

    $('.popup-exit').click(function () {
        clearPopup();

    });

    $('.popup-overlay').click(function () {
        clearPopup();
    });

    function clearPopup() {
        $('.popup.visible').addClass('transitioning').removeClass('visible');
        $('html').removeClass('overlay');

        setTimeout(function () {
            $('.popup').removeClass('transitioning');
        }, 200);
    }

});
$(document).ready(function(){
  $('.pagination').hide();
});
</script>

app/views/tasks/task_down.js.erb
// For swapping two panel contents after changing position //
setTimeout(function(){
$("#tasks_lists").html("<%= j(render(partial:@tasks)) %>");
}, 250);

app/views/tasks/task_requests.js.erb
$("#show_tabs").html("<%= escape_javascript(render partial: 'task_requests') %>");

app/views/tasks/task_up.js.erb
setTimeout(function(){
$("#tasks_lists").html("<%= j(render(partial:@tasks)) %>");
}, 250);