config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :tasks do
    member do
      get 'confirm_delete'
      get 'task_completion'
      get 'add_participants', as: :add_participants
      get 'task_up'
      get 'task_down'

    end
    collection do
      get 'active_tasks', :as => :active
      get 'completed_tasks', :as => :completed
      get 'task_requests', :as =>:requests
      post :remove_share
    end
    resources :comments
  end
  resources :participants do
    member do
      get 'accept_request'
      get 'set_progression'
    end
    collection do
      post :set_progression
      get :autocomplete_user_name
      get :check_existence
    end

  end

  root 'tasks#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :participants,  dependent: :destroy
  has_many :tasks, through: :participants,  dependent: :destroy
  has_attached_file :avatar, styles: { medium: '200x200>', thumb: '30x30>' }, default_url: '/images/:attachment/missing_:style.png'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  scope :other_users, -> { where.not(id: Todo.current_user.id) }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_user, except: :index
  respond_to :html, :js

  def index
    @users = User.all
  end

  def show
    if current_user == @user
      flash.now[:notice] = 'Your profile is not complete ! Complete now' unless @user.avatar_file_size.present?
    end
    @tasks = Task.where(user_id: params[:id])
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to @user, notice: 'Saved succesfully'
    else
      redirect_to @user, notice: 'Saving not success'
    end
  end

  def destroy
    current_user.destroy
    redirect_to root_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :avatar, :about)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit.html.erb
<!-- User edit modal box -->
<div class = "jumbotron">
  <%= form_for current_user ,html: { multipart: true } do |f|%>
    <div class = "prof_img">
      <%= image_tag current_user.avatar.url(:medium), class: "img-circle" %>
    </div>
    <%=  f.text_field :name, class:'form-control', autofocus:true %>
    <%=  f.text_area :about, class:'form-control', autofocus:true, placeholder: "About You" %>
    <span class="btn btn-default btn-file">
      Select Profile Picture <%= f.file_field :avatar, class:'btn btn-warning form-control' %>
    </span>
    <div class = "col-sm-12 row user_save">
    <%= f.submit :submit, value: "Save", class: 'share_link save pull-left' %>
  <% end %>
  <%= link_to ("<div class = 'delete_confirmation_cancel_button pull-left popup-exit'><u>Cancel</u></div>").html_safe, :rel => "modal:close" %>
    </div>
    
</div>

app/views/users/index.html.erb
<!-- Users Index Page -->
<div class = "row">
  <ul class="col-sm-12 list-group users">
    <% @users.each do |user| %>
      <% unless user.id == current_user.id %>

        <li class="list-group-item user">
          <span class = "dp"><%= image_tag user.avatar.url(:thumb), class: "img-circle" %></span>&nbsp;
          <span class="badge"><%= number_to_human(user.tasks.count)%></span>
          <%= link_to user.name, user_path(user.id) %>
        </li>
      <% end %>
    <% end %>
  </ul>

</div>

app/views/users/show.html.erb
<div class = "jumbotron">
  <div class = "row">
    <div class = "col-sm-12">
      <div class = "col-sm-6"><!-- User Display Picture -->
        <%= image_tag @user.avatar.url(:medium), class: "img-thumbnail" %>
      </div>
      <div class = "col-sm-6">
        <div class = "col-sm-12 user_show_name text-uppercase">
          <%= @user.name %>
        </div>
        <div class ="col-sm-12 user_show_details">
          <span class = "label label-success"><u><%= number_to_human(@tasks.count)%></u> Own Tasks</span>
          <span class = "label label-warning"><u><%= number_to_human(@user.tasks.count) %></u> Working Tasks</span>
        </div>
        <div class = "col-sm-12 user_show_description">
          <%= link_extract(@user.about).html_safe %>
        </div>
      </div>
    </div>
    <div class = "col-sm-12 ">
      <div class = "edit_profile_link">
        <% if @user.id == current_user.id %>
          <%#= link_to_modal ("<div class = 'share_link'>Edit Profile</div>").html_safe, edit_user_path(@user.id), data:{remote: true} %>
           <div id="example-popup" class="popup">
            <div class="popup-body">
              <%=render 'edit' %>
            </div>
          </div>
          <div class="popup-overlay"></div>
          <div class="share_link" data-popup-target="#example-popup">
            Edit
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function() {

    $('[data-popup-target]').click(function () {
        $('html').addClass('overlay');
        var activePopup = $(this).attr('data-popup-target');
        $(activePopup).addClass('visible');

    });

    $(document).keyup(function (e) {
        if (e.keyCode == 27 && $('html').hasClass('overlay')) {
            clearPopup();
        }
    });

    $('.popup-exit').click(function () {
        clearPopup();

    });

    $('.popup-overlay').click(function () {
        clearPopup();
    });

    function clearPopup() {
        $('.popup.visible').addClass('transitioning').removeClass('visible');
        $('html').removeClass('overlay');

        setTimeout(function () {
            $('.popup').removeClass('transitioning');
        }, 200);
    }

});
</script>