config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :tasks do
    member do
      get 'confirm_delete'
      get 'task_completion'
      get 'add_participants', as: :add_participants
      get 'task_up'
      get 'task_down'

    end
    collection do
      get 'active_tasks', :as => :active
      get 'completed_tasks', :as => :completed
      get 'task_requests', :as =>:requests
      post :remove_share
    end
    resources :comments
  end
  resources :participants do
    member do
      get 'accept_request'
      get 'set_progression'
    end
    collection do
      post :set_progression
      get :autocomplete_user_name
      get :check_existence
    end

  end

  root 'tasks#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoHub</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= Gon::Base.render_data %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
</head>
<body>

  <div class = "container">
    <% if current_user %>
    <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
          <%= link_to ('<div class = "logo head"></div>').html_safe, root_path %>
      </div>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <div class="dropdown">
          <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown"><%= current_user.name %></button>
          <ul class="dropdown-menu">
            <li class="dropdown-header"><%= current_user.email %></li>
            <li><%= link_to "Show Profile", user_path(current_user) %></li>
            <li><%= link_to "Users List", users_path%></li>
            <li class="divider"></li>
            <li class="dropdown-header">Account</li>
            <li><%= link_to "Logout", destroy_user_session_path , method: :delete %></li>
            <li><%= link_to "Delete Account", user_path(current_user.id) ,data: {confirm: "Are you sure?"}, method: :delete %></li>
          </ul>
        </div>
      </li>
    </ul>
    </div>
  </nav>
  <% end %>
  <% flash.each do |name, msg| %>
        <div class="alert alert-info alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <strong></strong> <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
  <% end %>
    <%= yield %>
    <div class="pagination">

    </div>
  </div>

  <script>
    $(document).ready(function(){
        $('[data-toggle="popover"]').popover();
    });
  </script>
</body>
</html>

app/views/layouts/session_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoHub</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
</head>
<body>

  <div class = "container">
    <div class="row">
      <div class = "col-sm-12">
        <%= link_to ('<div class = "logo"></div>').html_safe, root_path %>
      </div>
    </div>

    <%= yield %>
  </div>

  <script>
    $(document).ready(function(){
        $('[data-toggle="popover"]').popover();
    });
  </script>
</body>
</html>